version: "3"
services:
  client:
    build: .
    image: spa_react_js_hello-world_react-router-6:starter
    container_name: spa_react_js_hello-world_react-router-6_starter
    ports:
      - 4040:4040
      - 6060:6060
    env_file:
      - .env
